############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "RES Device"
url = "project/"
weight = 3

[[main]]
weight = 5
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Pricing"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "RES Device"
url = "project/"
weight = 3


[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7